services:
  sharemate-gateway:
    build: sharemate-gateway/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - sharemate-server

  sharemate-server:
    build: sharemate-server/.
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  sharemate-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sharemate-spring-boot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - sharemate-db-data:/var/lib/postgresql/data
volumes:
  sharemate-db-data: